// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chord.proto

// Protobuf Java Version: 3.25.3
package dev.serathiuk.chord.grpc;

public final class ChordOuterClass {
  private ChordOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013chord.proto\"\024\n\006NodeId\022\n\n\002id\030\001 \001(\t\".\n\004N" +
      "ode\022\n\n\002id\030\001 \001(\t\022\014\n\004host\030\002 \001(\t\022\014\n\004port\030\003 " +
      "\001(\r\"#\n\005Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      "\"P\n\013PutResponse\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t\022\016\n\006nodeId\030\003 \001(\t\022\025\n\rputInNextNode\030\004 \001" +
      "(\010\"\031\n\nGetRequest\022\013\n\003key\030\001 \001(\t\"P\n\013GetResp" +
      "onse\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022\016\n\006node" +
      "Id\030\003 \001(\t\022\025\n\rgetInNextNode\030\004 \001(\010\"\007\n\005Empty" +
      "2\350\001\n\005Chord\022\037\n\016getPredecessor\022\006.Empty\032\005.N" +
      "ode\022\035\n\014getSuccessor\022\006.Empty\032\005.Node\022\037\n\rfi" +
      "ndSuccessor\022\007.NodeId\032\005.Node\022&\n\024closestPr" +
      "ecedingNode\022\007.NodeId\032\005.Node\022\027\n\006notify\022\005." +
      "Node\032\006.Empty\022\033\n\003put\022\006.Entry\032\014.PutRespons" +
      "e\022 \n\003get\022\013.GetRequest\032\014.GetResponseB\034\n\030d" +
      "ev.serathiuk.chord.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NodeId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NodeId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Node_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Node_descriptor,
        new java.lang.String[] { "Id", "Host", "Port", });
    internal_static_Entry_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PutResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PutResponse_descriptor,
        new java.lang.String[] { "Key", "Value", "NodeId", "PutInNextNode", });
    internal_static_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetResponse_descriptor,
        new java.lang.String[] { "Key", "Value", "NodeId", "GetInNextNode", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
