// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chord.proto

// Protobuf Java Version: 3.25.3
package dev.serathiuk.chord.grpc;

public interface PutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nodeId = 1;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string nodeId = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();
}
