// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chord.proto

// Protobuf Java Version: 3.25.3
package dev.serathiuk.chord.server.grpc;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>string nodeId = 3;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string nodeId = 3;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>bool getInNextNode = 4;</code>
   * @return The getInNextNode.
   */
  boolean getGetInNextNode();
}
